version: '3.9'

services:
  app:
    container_name: app
    image: bgma_devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ..:/workspaces/bgma
      - node_modules:/workspaces/bgma/node_modules
      - next:/workspaces/bgma/.next
      - ~/.ssh:/home/node/.ssh
    networks:
      - dev_network

volumes:
  node_modules:
    name: bgma_node_modules
  next:
    name: bgma_next

networks:
  dev_network:
    name: bgma_dev_network
