version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ..:/workspaces/app
      - node_modules:/workspaces/app/node_modules
      - next:/workspaces/app/.next
      - ~/.ssh:/home/node/.ssh

volumes:
  node_modules:
    name: bgma_node_modules
  next:
    name: bgma_next
